### ISSUE TITLE
Add description to the name

### ISSUE THREAD

**Issue by utkarsh2102** [chromatic/Modern-Perl#12]
Hey,

While maintaining this package in Debian, we are applying this patch; thought you'd be interested in this?

```
--- a/lib/odern/Perl.pm
+++ b/lib/odern/Perl.pm
@@ -14,7 +14,7 @@
 
 =head1 NAME
 
-odern::Perl
+odern::Perl - Module for enabling all of the features of Modern Perl
 
 =head1 VERSION
```

**Comment by chromatic** [comment]
Looks good. Thank you!

This has been released as Modern::Perl 1.20190727.

**Comment by scottchiefbaker** [comment]
I'm confused... why is the name `odern` without the "M"

**Comment by chromatic** [comment]
This lets you write on the command line `perl -Modern::Perl=2019 -e '...'`, for example. It's just a silly little convenience that costs very little to support but reads well.
