### ISSUE TITLE
Experimental features?

### ISSUE THREAD

**Issue by gryphonshafer** [chromatic/Modern-Perl#3]
What do you think about optional enabling of experimental features? The usefulness would be minimal, just letting me avoid having to type a couple extra lines. I'm thinking of maybe an interface like this:

```
use Modern::Perl qw( 2016 signatures );
```

And that would be the equivalent of:

```
use Modern::Perl '2016';
use feature 'signatures';
no warnings 'experimental::signatures';
```

(Yes, I'm really that lazy.)

Also, maybe a mean to include all experimental features for the version?

```
use Modern::Perl qw( 2016 :xall );
```

**Comment by chromatic** [comment]
I'm open to this idea, if there's a new namespace something like `Modern::Perl::Experimental` or `Modern::Perl::Experiments`, which supported both the '2016' argument as well as some syntax along the lines of what you propose.
