### ISSUE TITLE
"Toolkit" bundle?

### ISSUE THREAD

**Issue by gryphonshafer** [chromatic/Modern-Perl#4]
What do you think about the idea of adding a module list bundler like what Toolkit provides? I can't say I'm a fan of how Toolkit gets the bundles (out of a file in $PERL5LIB). I'd prefer by default nothing happens, but then if a user specifies "kit" or something, the module looks for a ".mpkit" file or something up the tree.

```
use Modern::Perl qw( 2016 kit );
```

Or maybe specify the kit location:

```
use Modern::Perl qw( 2016 kit:~/.mpkit );
```

I don't know. I'm not super excited about the interface. Just sharing some ideas. What do you think?

**Comment by chromatic** [comment]
Like you say, the interface doesn't quite seem right. More than that, I'm leery to add anything beyond "enable the core features that Perl 5.24 would enable by default if not for forward compatibility concerns". Closing for now, in lieu of an interface suggestion we both prefer.
