### ISSUE TITLE
Duplicate copyright section

### ISSUE THREAD

**Issue by jonjensen** [chromatic/Modern-Perl#8]
First, thanks for this module. It gets used. :)

Minor nit: There's a redundant copyright section at the bottom here:

https://metacpan.org/pod/Modern::Perl

but it's not in the actual `lib/Modern/Perl.pm` source file, so maybe it's being added by your packaging tools?

**Comment by chromatic** [comment]
Looks like this has been fixed in a subsequent update. Thanks for reporting!
