### ISSUE TITLE
Tests fail if PERL5OPT is set

### ISSUE THREAD

**Issue by bigpresh** [chromatic/Modern-Perl#9]
In my .profile, I set `PERL5OPT=-M5.010`, so that `say` etc are always available to me.

When I try to install Modern::Perl, it fails some of its tests, because of this.

If I unset PERL5OPT, it passes and installs fine.

Whilst, yes, the problem is my own doing, I think it may be sensible for it to unset it automatically, or detect that it was set and skip tests.  (i.e. to realise that "yes, `say` is available when we don't expect it to be, but that's because the user set an env var that asks for it, not because the code is broken").

**Comment by chromatic** [comment]
Thanks for reporting! Fixed in 590f9cd and the 1.20180901 release.
